#Gradle Properties
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
#Fabric Properties
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.16.3
# Mod Properties
mod_id=tb-addon
mod_name=TBAddon
mod_description=A Hypixel Skyblock odin addon
mod_version=0.0.3
maven_group=com.odtheking
archives_base_name=odin-addon
# Mod Dependencies
fabric_kotlin_version=1.13.12+kotlin.2.4.0
fabric_api_version=0.151.0+26.1.2
kotlin_loader_version=1.13.12+kotlin.2.4.0
devauth_version=1.2.2
commodore_version=1.0.1
iris=1.10.9+26.1-fabric
modmenu_version=18.0.0-beta.1
# Other Properties
kotlin_version=2.4.0
kotlin.code.style=official
minecraft_lwjgl_version=3.4.1
# 0.3.0
odin_version=0.3.0
